export const colors = {
  HEADER_BACK_COLOR_LIGHT: '#3E50B5',
  HEADER_BACK_COLOR_DARK: '#272727',
  HEADER_TEXT_COLOR_NAV_DARK: '#FF652F',
  HEADER_TEXT_COLOR_LOGO_DARK: '#FFE400',
  HEADER_TEXT_COLOR_DEFAULT_DARK: '#14A76C',
  HEADER_CHECKBOX_COLOR_DARK: '#BABABA',
  BORDER_COLOR: '#979797',
  DELETE_BUTTON_COLOR: '#FF4081',
  SWITCH_THEME_COLOR: '#646464',
}
